# Generated by Django 5.2.8 on 2026-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CouponUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("id_card", models.CharField(max_length=20)),
                ("occupation", models.CharField(max_length=100)),
                ("income_level", models.CharField(max_length=100)),
                ("coupon_code", models.CharField(max_length=50)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
