# Generated by Django 5.2.8 on 2026-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("company", models.CharField(max_length=200)),
                ("visit_reason", models.CharField(max_length=200)),
                ("host_name", models.CharField(max_length=100)),
                ("visit_time", models.DateTimeField()),
            ],
        ),
    ]
