# Generated by Django 5.2.8 on 2026-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParcelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("id_card", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("parcel_no", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
